package(
    default_visibility = ["//:__subpackages__"],
)

py_library(
    name = "base",
    srcs = ["base.py"],
)

py_library(
    name = "linebase",
    srcs = ["linebase.py"],
    deps = [":base"],
)
